on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx4g -Xms1g -XX:MaxPermSize=2048m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError" -Dfile.encoding="UTF-8" -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true
    steps:
      - uses: actions/checkout@v4
      - name: Increase swapfile
        run: |
          sudo swapoff -a
          sudo fallocate -l 15G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          sudo swapon --show
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt-openj9'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build with Gradle
        run: ./gradlew build --no-daemon
